name: cosif
channels:
  - conda-forge
dependencies:
  # Core python
  - python=3.9
  - black
  - jupyterlab
  - numpy
  - numba
  - pandas
  - scipy
  # Data management
  - xarray=2022.10.0
  - rioxarray
  - dask
  - netcdf4
  - h5netcdf
  - h5py
  - rasterio
  - xesmf
  # Statistics / ML
  - scikit-learn
  - statsmodels
  # Plotting
  - matplotlib=3.4
  - seaborn
  - cartopy
  - cmcrameri
